### ISSUE TITLE
SynBioHub does not allow browsing access to measurement objects

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#1010]
Consider the following:
https://hub.sd2e.org/user/sd2e/design/culture_media_1/CAT_BP382_100/1/7a4d579d600a29522c45d2d46f9d21b38dedbef2/share

There is an om-2#measure object on this, but one cannot actually open it up, it just says "1" and is not shown nor browsable.

cc: @dashaveraksa

**Comment by cjmyers** [comment]
This link is not browsable because the linked object:

https://hub.sd2e.org/user/sd2e/design/culture_media_1/CAT_BP382_100/CAT_BP382_100_measure/1

does not exist in SBH.  My guess is this object was not uploaded or it was removed.  Do you have the original object that was uploaded?  It is possible that somehow that part of the object did not get uploaded properly.

**Comment by jakebeal** [comment]
In that case, it looks like measure information has been somehow getting systematically removed... do you have _any_ example of an object in a SynBioHub with measure information?  @dashaveraksa needs examples to compare against, and I can't find any.

**Comment by cjmyers** [comment]
Are you talking about the new Measure class?  This looks like it is not being correctly setup, since Measure does work, see here:

https://synbiohub.utah.edu/user/myers/Measure/Measure_collection/1/341c35c879421e57dda0f37ce40ce1e7306eed99/share <https://synbiohub.utah.edu/user/myers/Measure/Measure_collection/1/341c35c879421e57dda0f37ce40ce1e7306eed99/share>

Click through to see Measures on FC and Modules.

**Comment by jakebeal** [comment]
Perfect, thank you!  @dashaveraksa, here is your example of a Measure to match --- in the current SynBioHub is even shows up in it's own special set of Measure properties.
