### ISSUE TITLE
Experimental data errors

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#1031]
When one clicks an ExperimentalData object in the SD2 SynBioHub instance right now, one gets a page with the following error:

> Error: ENOENT: no such file or directory, open 'templates/views/experimentaldata.jade'

**Comment by cjmyers** [comment]
Duplicate to #1021

**Comment by cjmyers** [comment]
Fixed on staging, see for example:

https://hub-staging.sd2e.org/user/sd2e/biofab_yeast_gates_q0_aq_10833/s2341_R3593_R11707_R27855_flowCytometry_11/1

**Comment by jakebeal** [comment]
Great, thank you.

**Comment by jakebeal** [comment]
When is this getting pushed to production?

**Comment by cjmyers** [comment]
We have not done this, since this is essentially the only difference from 1.5.2 to 1.5.3 so far.  We have been hoping to get auth done too, but that is still stalled on testing.  I would also like to get libSBOLj updates for handling multiple locations correctly, but I’ve also been swamped and unable to find cycles on that.  Do you want to wait for either of these things, or do you want us to cut a release after Thanksgiving regardless of the progress on these two things?
