### ISSUE TITLE
Create collection for each keyword

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#106]
This would allow us to remove the synbiohub keyword predicate.

**Comment by cjmyers** [comment]
Or add member to if existing.

**Comment by cjmyers** [comment]
This looks promising:

http://www.quasipartikel.at/multiselect/

**Comment by cjmyers** [comment]
Each Keyword should come from the Keyword collection.

Question: should we change Keywords to Collections and then allow one to add to any Collection?

**Comment by cjmyers** [comment]
https://harvesthq.github.io/chosen/

**Comment by cjmyers** [comment]
A new submission can now be added to existing public collections.  This is done in two steps.  In step 1, the TopLevels are tagged on submission with a SBH annotation isMemberOf.  In step 2, when make public is done, it adds these top levels as members of the public collection.

NOTE: TopLevels added in this way are not returned when the Collection is downloaded.  The reason is that these members do not have this collection as a rootCollection annotation.  Should they?  Or should we rethink the download of collection SBOL for non-root Collections.

**Comment by cjmyers** [comment]
Solution is to replace rootCollection with isMemberOf and use that for all collection fetches.

**Comment by cjmyers** [comment]
Done
