### ISSUE TITLE
Creation of collections should happen in conversion/validation stage

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#116]
Currently the submission process, from the input file, is:

* Convert to SBOL2 and change URI prefixes using external service
* Load as SBOL document
* Create collections
* Serialize
* Send to triplestore

This could be significantly faster if SynBioHub itself never loaded the SBOL document.  The collections would instead be created by the libSBOLj web service:

* Convert to SBOL2, change URI prefixes, and create collections using external service
* Send to triplestore

**Comment by udp** [comment]
This would mean we would need our own service separate from the Utah converter/validator.  I think the converter/validator should be bundled with SynBioHub anyway, though.

**Comment by cjmyers** [comment]
Agreed on making local validator part of the synbiohub install.

As for submission process, it is not that bad currently.  The only loading of SBOL is done from the file return from the converter which is pretty fast.  The slow step is pulling the SBOL back out of the triple store.  This is what happens during make public, since it must fetch the SBOL to send to validator.  Your scheme does not solve this issue.  We need a faster way to pull large SBOL records out of a triple store.

I think the solution to this is related to improve queries to build SBOL like we discussed at lunch.

Chris
