### ISSUE TITLE
Attachurl broken

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1180]
AttachURL crashes SynBioHub

**Comment by cjmyers** [comment]
@jvscholz I cannot reproduce this one.  The problem I saw was different.  I chose a name that was same as an existing Collection which put things in a strange state.  This should probably be checked though in the future.

If you can reproduce, can you tell me exactly what you enter into the fields.

**Comment by jvscholz** [comment]
@cjmyers, I used the url:

> meowmeowmeowmeow.com

[https://i.imgur.com/R0arBhE.png](scerenshot)

**Comment by jvscholz** [comment]
I suspect it's because I left the name field blank, however, once I put in a URL the attach button becomes green like it's ready to go. Maybe the attach button should only become green once a name is inputted?

**Comment by cjmyers** [comment]
Looks like the problem comes when now Attachment type is selected:

error: (node:31620) UnhandledPromiseRejectionWarning: Error: Virtuoso 37000 Error SP030: SPARQL compiler, line 16: syntax error at '<' before 'Pick'

SPARQL query:
define sql:big-data-const 0 define input:default-graph-uri <https://synbiohub.org/user/myers> PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>
PREFIX sbol: <http://sbols.org/v2#>

INSERT {
    <https://synbiohub.org/user/myers/testAPI/testAPI_collection/1> sbol:attachment <https://synbiohub.org/user/myers/testAPI/fd4549bf-758d-4d3b-bf11-44d69e502f80/1> .

    <https://synbiohub.org/user/myers/testAPI/fd4549bf-758d-4d3b-bf11-44d69e502f80/1> a sbol:Attachment ;
        dcterms:title "fd4549bf-758d-4d3b-bf11-44d69e502f80" ;
        sbol:displayId "fd4549bf-758d-4d3b-bf11-44d69e502f80" ;
        sbol:persistentIdentity <https://synbiohub.org/user/myers/testAPI/fd4549bf-758d-4d3b-bf11-44d69e502f80> ;
        sbol:version "1" ;
        sbh:ownedBy <https://synbiohub.org/user/myers> ;
        sbh:topLevel <https://synbiohub.org/user/myers/testAPI/fd4549bf-758d-4d3b-bf11-44d69e502f80/1> ;
        sbol:source <http://meowmeowmeowmeow.com/> ;
        sbol:format <Pick an attachment type...> .
} 


    at Request.request [as _callback] (/Users/myers/git/synbiohub/lib/sparql/sparql.js:47:16)
    at Request.self.callback (/Users/myers/git/synbiohub/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/myers/git/synbiohub/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/myers/git/synbiohub/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
error: (node:31620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
error: (node:31620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cjmyers** [comment]
@3ach any ideas here?  Looks like there is a bad project reject in sparql/sparql.js.  We should fix this first, then we should also change it so attach is only enabled once the URL, name, and type are all provided.
