### ISSUE TITLE
Remove owner isn't uniform with add owner

### ISSUE THREAD

**Issue by jvscholz** [SynBioHub/synbiohub#1211]
Endpoints are inconsistent with each other

POST <URI>/addOwner

curl -X POST -H "Accept: text/plain" -H "X-authorization:59763b66-ce63-471b-ac1e-2cfcb9926bb0" -d "user=dockertestuser&uri=http://localhost:7777/user/testuser/bruh/bruh_collection/1/addOwner" http://localhost:7777/user/testuser/bruh/bruh_collection/1/addOwner

POST <URI>/removeOwner/<username>

curl -X POST -H "Accept: text/plain" -H "X-authorization:<>" -d "userUri=<>" http://synbiohub.org/public/:collectionId/:displayId/:version/removeOwner/:username

**Comment by cjmyers** [comment]
I understand it is not uniform from an API perspective, but it is this way due to the GUI.  Namely, in the browser, when you add an owner, you select from a list, and it is sent via a post request.  When you remove owner, you find the user in the list of owners, and you click on the one to remove, so easier to add in the URL.  I think we will leave this for now, especially since it will be replaced in the new auth module.
