### ISSUE TITLE
Search endpoint returns 404 when no results are found

### ISSUE THREAD

**Issue by tcmitchell** [SynBioHub/synbiohub#1252]
At present the [search metadata endpoint](https://synbiohub.github.io/api-docs/#search-metadata) returns a 404 when the search returns no results. This is indistinguishable from a malformed URL error message.

It would be better from a client perspective to return an empty JSON list to indicate that the search was successful and found no matching records.

**Comment by cjmyers** [comment]
I think this might actually be an SBOLExplorer issue.  I cannot seem to reproduce with SBOLExplorer not enabled.  It seems to return an empty set in that case.  My guess is SBOLExplorer is returning 404 rather than an empty search list.  If SBOLExplorer is failing, it should invoke the default search in SBH.  If SBOLExplorer is actually getting no results, it should return an empty list.

**Comment by cjmyers** [comment]
Hmm, nevermind, I turned off SBOLExplorer and same message.  Not sure now.

**Comment by cjmyers** [comment]
This query returns no results:

curl -X GET -H "Accept: text/plain" 'https://synbiohub.org/search/objectType%3D%3Chttp%3A%2F%2Fsbols.org%2Fv2%23ComponentDefinition%3E%26sbol2%3Arole%3D%3Chttp%3A%2F%2Fidentifiers.org%2Fso%2FSO%3A0000318%3E%26GFP'

It does not return 404.  So the theory that the 404 is due to no results is wrong.  This seems to somehow be unique to the Utah server.  I cannot find anywhere in the code where it would return this error on a search.

**Comment by cjmyers** [comment]
Ok, even more tests.  This is definitely a problem with the Utah server setup.  I've tried other SBHs, and they don't have this issue.

**Comment by cjmyers** [comment]
So, I think I have a better idea of the problem but no idea for the solution.  The key difference with this server and others is that it uses Apache.  Others are using nginx and caddy.  I think the issue is perhaps do to the apache config for SBH (synbiohub.conf file) and maybe this line:

RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

I have no clue how to fix it.  Can you test search using different SBHs?  This one is likely not going to around forever anyway.

**Comment by tcmitchell** [comment]
Yes, we can search using different SBHs. Sorry to open Pandora's box, and thanks for all the hunting and detective work
