### ISSUE TITLE
Error when trying to remove a submission that was shared with me

### ISSUE THREAD

**Issue by aromanowski** [SynBioHub/synbiohub#1265]
I was testing the possibility of having a submission shared with me, modifying the description and then relinquish my ownership after finishing the edits. I was able to do the first two. However, when trying to remove the shared submission (to relinquish my ownership and leave it with the original owner), I got the following error:

users involved: aromanowski (owner), georomano (editor)

Error
Error: getType: https://synbiohub.org/user/aromanowski/Testbed/Testbed_collection/1/91b316c1beb84dc08521669c676c649365ab3af4/share/removeCollection not found
    at sparql.queryJson.then (/synbiohub/lib/query/local/type.js:12:29)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

Could you please help me solve this?

Thank you!

**Comment by cjmyers** [comment]
The problem is that remove collection is not the correct way to relinquish co-ownership.  In fact, a user with a shared link likely is not allowed to remove collection, since they don't have it in their own private repository.  We should hide that option in the shared records to avoid this confusion.  We should also add an option to allow a user to relinquish their shared access.

It should be noted that @3ach has developed a completely new authentication module for sharing, and it is nearly complete.  This should address some of your issues, but I'm not sure that we thought about giving up ownership as opposed to having it revoked.

**Comment by aromanowski** [comment]
Great, those are excellent solutions. Indeed as I did not see a relinquish ownership button (that would be amazing for research data curators, such as myself, that need to edit metadata and then relinquish ownership) I thought the proper procedure was to remove the collection.
I will be waiting eagerly for the upgrade in the authentication module.

Thank you!

**Comment by cjmyers** [comment]
Need to verify in the new authentication module that only users with highest permissions get rights to remove a shared object.  Also, need a means to relinquish sharing rights.
