### ISSUE TITLE
Genbank export problem

### ISSUE THREAD

**Issue by NeilWipat** [SynBioHub/synbiohub#1361]
Exporting an annotated  Genbank formatted file, doesn't export the correct sequence.

e.g. 

https://synbiohub.org/public/igem/BBa_G00001_sequence/1

Fasta Export:

>BBa_G00001_sequence (21 bp)
tactagtagcggccgctgcag

Genbank Export:

LOCUS       Exported                 180 bp ds-DNA     linear   UNA 03-OCT-2020
DEFINITION  natural linear DNA
ACCESSION   BO_29438
VERSION     .
KEYWORDS    .
SOURCE      natural DNA sequence
  ORGANISM  unspecified
REFERENCE   1  (bases 1 to 180)
  AUTHORS   .
  TITLE     Direct Submission
  JOURNAL   Exported Oct 3, 2020 from SnapGene Server 2.0.9
            http://www.snapgene.com
FEATURES             Location/Qualifiers
     source          1..180
                     /organism="unspecified"
                     /mol_type="genomic DNA"
ORIGIN
        1 gtggaagaga aatacgaaac aaacggatat gacacttcaa tcgtatatga ttacaaagaa
       61 tatcctgatg taaaatacgg ccgctgcgac aattgtgatt acactttgtt taaaagctct
      121 gtgaagagtg gaatattttt acgtgaatgc agaaggtgtg gcatgaaaaa gagcatttag
//

**Comment by cjmyers** [comment]
This is actually being generated by SnapGene's autoannotation tools  rather than SynBioHub using plugins.  This is a bug that we have fixed in the latest version, but we have not yet deployed this release yet.  You can see that it works on the dev server here:

https://dev.synbiohub.org/public/igem/BBa_G00001_sequence/1
