### ISSUE TITLE
Can't download genbank for bacillondex parts

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#175]
Validator says

> ComponentDefintion http://synbiohub.org/public/vpr/BO_10000/1 does not have an IUPAC sequence.

**Comment by udp** [comment]
Also note there's a typo in "ComponentDefintion" there. not sure whether that should be reported in libSBOLj or the validator.

**Comment by cjmyers** [comment]
My understanding is GenBank format is not for Protein sequences, see here:
https://www.ncbi.nlm.nih.gov/genbank/samplerecord/#MoleculeTypeB
and here
https://www.ncbi.nlm.nih.gov/Sequin//sequin.hlp.html#SpecifyMolecule
If you disagree, can you show me where it says it can be a protein?

Also, where is the typo?

**Comment by 16zzundel5** [comment]
From https://www.ncbi.nlm.nih.gov/books/NBK50679/#RefSeqFAQ.what_is_a_reference_sequence_r, 

> ... Whereas the International Nucleotide Sequence Database Collaboration (INSDC, made up of GenBank, the European Nucleotide Archive, and the DNA Data Bank of Japan) ...

The clear inference is that GenBank represents nucleotide sequences, and nucleotides are not components in proteins -- amino acids are. 

Also, there was a slight typo in the error messaging (it was ComponentDefintion, not ComponentDefin**i**tion) that I've fixed in libSBOLj.
