### ISSUE TITLE
Remotes editable in admin

### ISSUE THREAD

**Issue by 16zzundel5** [SynBioHub/synbiohub#324]

**Comment by 16zzundel5** [comment]
Remove button added in admin, still need the add

**Comment by cjmyers** [comment]
What is the Copy To SynBioHub button here for?

Below is the current configuration I’m using for a local ICE instance:

    "local_ice": {
      "id": "local_ice",
      "type": "ice",
      "url": "https://localhost:8443",
      "groupId": 2,
      "PI": "Chris Myers",
      "PIemail": "myers@ece.utah.edu",
      "X-ICE-API-Token-Client": "synbiohub.org",
      "X-ICE-API-Token": “<API KEY>",
      "X-ICE-API-Token-Owner": "Administrator",
      "rejectUnauthorized": false,
      "iceCollection": "FEATURED",
      "folderPrefix": "local_ice_folder_",
      "sequenceSuffix": "_sequence",
      "rootCollection": {
        "displayId": "local_ice_collection",
        "name": "Local ICE",
        "description": "Local collection of parts"
      }
    },

All of this information needs to be editable.  There are three new fields you may not be aware of: groupId, PI, and PIemail, which are used on part creation in ICE.  These still may change, so we just need to have an easy way to update the fields as this evolves.  Still working out a few issues in regards to part creation on ICE.

For Benchling, we need to be able to edit the following:

   "cidarlab_benchling": {
      "id": "cidarlab_benchling",
      "type": "benchling",
      "url": "https://api.benchling.com/v1",
      "X-BENCHLING-API-Token": “<API KEY>:",
      "rejectUnauthorized": true,
      "folderPrefix": "folder_",
      "sequenceSuffix": "_sequence",
      "defaultFolderId": "lib_YDrXycAT",
      "rootCollection": {
        "displayId": "cidarlab_benchling_collection",
        "name": "Cidar Lab Benchling",
        "description": "Cidar Lab Benchling collection of parts"
      }
    }

Note that we must add “:” after the API_KEY due to a quirk in Benchling API interface.  

It is also possible to set a default ICE/Benchling instances (defaultICEInstance / defaultBenchlingInstance) which parts are always copied to.  This is useful if an instance only ever uses ones of these.  These are top-level config options.  Having a check box to mark a default ICE and/or Benchling instance would be nice but I would say make that a 1.1 feature.

**Comment by 16zzundel5** [comment]
It replaces the snapshot functionality

**Comment by cjmyers** [comment]
Ah, so it attempts to copy everything?

**Comment by 16zzundel5** [comment]
Yes, both you and @udp duplicated the idea of copying from the remote so I just unified it, no reason to do the same thing twice.

**Comment by cjmyers** [comment]
Are you using my copyFromRemote code?  Or did you actually weave the code somehow?

**Comment by 16zzundel5** [comment]
I didn't change the actual copy code, it's just pointing to your code.

**Comment by 16zzundel5** [comment]
PR #337
