### ISSUE TITLE
The fields on the create form need a help feature to explain to biologists what to enter - especially the ID field 

### ISSUE THREAD

**Issue by NeilWipat** [SynBioHub/synbiohub#357]

**Comment by cjmyers** [comment]
This is a duplicate issue with #354.

**Comment by cjmyers** [comment]
This issue stemmed from comments on #354.  One possible solution would be to have multiple tabs on the submit page for different types of submit.  Here are a few:

1) Creating a new collection, id would be required as before, but no file needs to be uploaded.
2) Uploading a design which will later be made public into an existing Collection.  The user does not need to provide an ID assuming we always allow the user to see the name.  Benchling and ICE create ids for the user in these cases.  The id is cryptic and not meaningful, but it is functional assuming there is a good name/description.  The tricky bit about this one would be to devise an ID that is available to use.  However, this should only be a search on the local graph, so it should not be too slow to find one.  Note, it likely will not be globally unique, but that is fine, since it is in the private store.

**Comment by cjmyers** [comment]
Added information buttons.

Leaving open but moving to 1.1, in case we still want to make default ids.

**Comment by cjmyers** [comment]
Add some margin on the info box for the overwrite.
