### ISSUE TITLE
Move the type column from the left hand side of tables

### ISSUE THREAD

**Issue by NeilWipat** [SynBioHub/synbiohub#358]
Biologists intuitively click on the left most column. At the moment this links through to the type definition which confuses them. Move the type column to somewhere else or remove the link.

**Comment by cjmyers** [comment]
What if we replace them with icons?  It would save space, and it would be much less tempting to click on.  We could have the following icons:

Collection : some sort of stack of papers
ComponentDefinition : could possibly use different icons for basic parts (i.e., SBOLv symbols) and composites
Sequences : a piece of DNA?
ModuleDefinition : maybe a box with ports in/out
Model : a graph
Attachement : a piece of paper
Other : ?

**Comment by NeilWipat** [comment]
I agree that we need to remove all trace of SBOL terms from the GUI. The role would be much more useful to have on display. A user shouldn’t need to see the SBOL types. Can we hide these somehow – maybe put the icons at the end?

**Comment by cjmyers** [comment]
The reason the types are there is because a Collection may include a lot of varied types of objects: Collections, Sequences, ComponentDefinitions, etc.  One solution is to make the Type not clickable (see ICE plot below, this is what they do).  I also still like the idea of using icons.  

One more thing I want to consider is a better filter on members.  What I mean by this is only showing the items that are not referenced by a child.  This would mean Collection page would only show Collections that are not members of any others within root Collection, only show Sequences if they are not linked to any ComponentDefinitions (should be very rare), only show Models if they are not linked to any ModuleDefinitions (again rare), and only show attachments that are not linked to any object (should never happen).  This will make the collection view a lot less cluttered.

**Comment by zachzundel** [comment]
I think this is a great idea, can you open the issue?

Thanks,
Zach

**Comment by cjmyers** [comment]
Done.

Chris

**Comment by cjmyers** [comment]
This is a duplicate issue with #363.
