### ISSUE TITLE
Need better error handling for webOfRegistries

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub#425]
There needs to be better error handling with WebOfRegistries, it should have code to catch errors and clean up the state appropriately, such as removing the web of registries secret.

**Comment by zachzundel** [comment]
If the URL is wrong (such as http instead of https) you get 502 error. Better error checking is needed.

Also if their are problems with web of registries information in the config, also 502.

In general, you are missing catch statements to present errors on better error pages.

-- @cjmyers on closed duplicate issue

**Comment by zachzundel** [comment]
I have implemented checks so that errors in the config are displayed on registries page and the user cannot even see the registration form unless they are fixed.
