### ISSUE TITLE
"What's a collection ID?"

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#484]
I just had Heather try to submit something as a test.  She signed up and got to the submission page, but had no idea what to put in the "collection ID" box.  She also didn't know if the references etc. were mandatory which put her off.

**Comment by udp** [comment]
I then asked her to send me it as SBOL.  She clicked Download SBOL, but was still on the collection, so I got an XML file with the collection but no parts in it.  I had to explain that she needed to click through to the component.

**Comment by udp** [comment]
Also, the part has now mysteriously disappeared from the collection (!!!)

**Comment by zachzundel** [comment]
The collection ID issue has been logged a couple of times. I'm not sure about the part disappearing, though.

**Comment by cjmyers** [comment]
How about we move the id/version after the name and description on the submit page?  Also, we can have the name become id'ified using the same scheme that Zach did for the username.  

Not sure why she was put off by the citations.  It clearly says at the top that only bold fields are required.  We could remove it from submission page, since it can always be added later.  The only advantage of removing for the collection is that it gets added recursively to everything at this point, but would perhaps add some other way to do this.  Note that I've removed the adding to collections here.  This will be done now when making public instead.

As for download SBOL, she did not have to go to the component to do this.  The reason why you only saw the Collection sounds like because there were no components submitted.  Did it disappear or did it just never get uploaded in the first place?  Did she actually confirm that it was uploaded?  Could you have her send the file she uploaded, so we can test it to see if it perhaps cannot be uploaded for some reason.  What format was the file?

**Comment by cjmyers** [comment]
Did you close this because you figured out the issues Heather had?  

I've opened a new issue about creating ids on the fly.
