### ISSUE TITLE
'Mirrored from Benchling' text persists

### ISSUE THREAD

**Issue by AGMoreno** [SynBioHub/synbiohub#509]
If a part is sent to Benchling, then you'll get the "Mirror from Benchling' text. After copying it to SynBioHub and delete it from Benchling, the only copy of the part lives in SynBioHub. However, it still says 'Mirrored from Benchling' at the top. If you click on that 'Benchling' word, you'll get an error (since the part was previously deleted from Benchling.

**Comment by cjmyers** [comment]
My guess is what you did is opened the part in SynBioHub, opened the part in Benchling using the linking, then removed it, then went back to your tab with the Benchling part in SynBioHub, correct?

If so, you are looking at a webpage that no longer exists.  If you go back to the Benchling collection and search for this page, I do not believe you will see it anymore since the part was removed from SynBioHub transfers.  There is no way I can think of to prevent this.  Think of this as the same as you submit a part to SynBioHub.  Open the page for that part.  Then go to another browser tab and remove the part, then go back to the other tab with the part.  It no longer exists, so the page you have open is stale.

Yet another example, you open a page on the web, then the webmaster deletes that page.  You still have the page open, but it does not exist anymore.  Essentially, your "cache" is stale.  I really cannot see any way to do anything about this. 

Please let me know if I'm misunderstanding.

**Comment by AGMoreno** [comment]
I know. I understand your point completely. It's just a usability thing.

After I copy the part in SynBioHub ('copy to sybiohub' button), I think
that part should be independent from Benchling. So the 'Mirror from
Benchling' sign would no longer be displayed. If not, deleting the part in
Benchling would end up in letting the 'Mirror from Benchling' sing on the
part from there onwards. Forever. And the link would be invalid.

A!

2017-10-20 15:06 GMT+01:00 cjmyers <notifications@github.com>:

**Comment by cjmyers** [comment]
I'm afraid you are still missing the point.  The link is not invalid.  If you refresh the page, you will find the link gone, indeed the whole page will be gone.  You just have a "cached" version that you are looking at.  When we view items in Benchling on SynBioHub, we are simply viewing what is in Benchling.  The page you are looking at is NEVER stored in SynBioHub.  It is created on the fly by querying Benchling.  We cannot update the page because the page simply does not exist anymore.

**Comment by AGMoreno** [comment]
The link is not gone. I can refresh the page, or close the computer and
access the part again. The "Mirrored from Benchling" quote will always be
there, living in my design forever. Since I deleted it from Benchling, the
link will go to an error page, obviously. I could click on "Send to
Benchling", so it will be sent again and the "Mirror from Benchling" will
point towards another copy of the design in Benchling, an existing one,
thus it will work.

Am I still getting it wrong?

2017-10-20 16:12 GMT+01:00 cjmyers <notifications@github.com>:

**Comment by cjmyers** [comment]
Please send the url so I can check. Thanks

Chris

**Comment by cjmyers** [comment]
Sorry Angel.  You are correct.  This is indeed a bug.  I just realized the reason for it.  The “Mirrored from Benchling” is created due to the presence of an annotation, which does get copied when it is moved from Benchling to SynBioHub.  It should indeed either not be copied or not displayed in this way when it is actually in SynBioHub.

Thanks for persisting on this.  Sorry if I was slow in understanding.

Chris

**Comment by cjmyers** [comment]
This should now be fixed on dev.synbiohub.org

To test, please go to https://dev.synbiohub.org and login

Then, take the URL you were using and add “dev.” before synbiohub.org and load that page.

You might also want to browse the Benchling collection to observe that the Mirrored at still exists for those parts.  

Let me know if this addresses your concern.

**Comment by AGMoreno** [comment]
Yes, it works! Thanks, A!

2017-10-21 15:46 GMT+01:00 cjmyers <notifications@github.com>:

> This should now be fixed on dev.synbiohub.org
>
> To test, please go to https://dev.synbiohub.org and login
>
> Then, take the URL you were using and add “dev.” before synbiohub.org and
> load that page.
>
> You might also want to browse the Benchling collection to observe that the
> Mirrored at still exists for those parts.
>
> Let me know if this addresses your concern.
>
>
