### ISSUE TITLE
Allow users to search for parts in the same way that Google allows searches

### ISSUE THREAD

**Issue by hsauro** [SynBioHub/synbiohub#56]
In the main search box, users should be allowed to type artibrary text and the backend will attempt to find corresponding parts. For novice users the web page should act like a Google search page so that there is no reason to go to the advanced searched window. 

eg

LacI GFP ecoli <- this would be equivalent to LacI and GFP and ecoli

More advanced queries 

LacI not ecoli <- finds all references to Laci not associated with ecoli.

etc

**Comment by cjmyers** [comment]
I think both of your requests essentially amount to adding Boolean connectives in string searches.  Since a sub-search is just:

<original search query> AND <new search query>

Correct?

The current behavior is a string of words is searched as an OR, so, if you type:

LacI GFP

You can think of it as:

LacI or GFP

It would be a simple matter to add a few “keywords” to search query.  Namely, “and”, “not”, “or”.  Am I missing anything from your two requests?

Chris

**Comment by cjmyers** [comment]
This should now be working at:

http://song.ece.utah.edu:7777

The following three queries produce the following results:

1) LacI GFP (equivalent to LacI or GFP) - 2526 results
2) LacI and GFP - 92 results
3) LacI and not GFP - 678 results

Please test and confirm if this fixes both your issues.

Thanks,

Chris

**Comment by cjmyers** [comment]
More general google searches likely possible once google indexes our pages.
