### ISSUE TITLE
Can't compile java parts

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#563]
mvn compile gives me:

> [ERROR] Failed to execute goal on project SynBioHub: Could not resolve dependencies for project org.synbiohub:SynBioHub:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.sbolstandard:libSBOLj:jar:2.2.2-SNAPSHOT, edu.utah.ece.async:iBioSim-conversion:jar:3.0.0-SNAPSHOT: Could not find artifact org.sbolstandard:libSBOLj:jar:2.2.2-SNAPSHOT in sems-maven-repo-snapshots (http://mvn.sems.uni-rostock.de/snapshots/) -> [Help 1]

**Comment by udp** [comment]
On OS X High Sierra,

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13", arch: "x86_64", family: "mac"
```

**Comment by udp** [comment]
This is because synbiohub references a version of libSBOLj which is not published on maven central, or on the other repository referenced by our pom.xml.  So you now need to download libSBOLj and install it manually from source before you can build synbiohub.

Please can you put the correct version of libSBOLj on either maven central or on another maven repo, and reference it from the SBH pom.xml.

**Comment by cjmyers** [comment]
This is correct.  We’ve changed SynBioHub to use Maven rather than local copies of jars.  So currently, you must install these dependencies and build them with “mvn install”.  You need libSBOLj, SBOLDesigner, and iBioSim.  You only need SBOLDesigner, because it is required to build iBioSim.  You need iBioSim for the SBML to SBOL conversion utility.

We are planning to release all of these libraries on maven central this week.  Zach is also working on setting up snapshot releases for these on sonatype for ongoing improvements.

**Comment by udp** [comment]
> You need iBioSim for the SBML to SBOL conversion utility.

What?  Why is this not a separate module?

**Comment by udp** [comment]
I don't even know where I would look to find the correct version of SBOLDesigner or iBioSim, and those are - sorry - completely stupid dependencies for SynBioHub to have.  At least sending some build instructions or JARs around first would have been nice.  Currently nobody apart from you and Zach can build SBH.

**Comment by cjmyers** [comment]
git clone https://github.com/SynBioDex/libSBOLj.git <https://github.com/SynBioDex/libSBOLj.git>
cd libSBOLj
mvn install
cd ..
git clone https://github.com/SynBioDex/SBOLDesigner.git <https://github.com/SynBioDex/SBOLDesigner.git>
cd SBOLDesigner
mvn install
cd ..
https://github.com/MyersResearchGroup/iBioSim.git <https://github.com/MyersResearchGroup/iBioSim.git>
cd iBioSim
mvn install
cd ..
cd synbiohub
cd java
mvn package

We were hoping to have all this in Maven soon, so none of this would be an issue.

**Comment by udp** [comment]
I'm not going to compile two large GUI applications in order to build the latest synbiohub, and neither are any other potential contributors.  We have people here I'm supposed to be showing how to work with the codebase and this is not helpful.

I would greatly appreciate it if you could either a) put the dependencies on Maven or b) provide a link to the compiled JARs.

**Comment by udp** [comment]
Tried to compile iBioSim and got (after ~20 minutes):

> [ERROR] Failed to execute goal on project iBioSim-dataModels: Could not resolve dependencies for project edu.utah.ece.async:iBioSim-dataModels:jar:3.0.0-SNAPSHOT: The following artifacts could not be resolved: org.sbml.libsbml:libsbml:jar:1.0.0, odk.lang:odk:jar:1.0.0, flanagan.math:flanagan:jar:1.0.0, org.jibble:epsgraphics:jar:1.0.0, org.jlibsedml:jlibsedml:jar:1.0.0: Could not find artifact org.sbml.libsbml:libsbml:jar:1.0.0 in ebi (http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/) -> [Help 1]

**Comment by chrisAta** [comment]
I've been trying to build SynBioHub, but instructions on the README.md didn't work due to a dependency on iBioSim still being present:

`[ERROR] Failed to execute goal on project SynBioHub: Could not resolve dependencies for project org.synbiohub:SynBioHub:jar:1.0.0-SNAPSHOT: Failure to find edu.utah.ece.async:iBioSim-conversion:jar:3.0.0-SNAPSHOT in http://mvn.sems.uni-rostock.de/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sems-maven-repository-snapshots has elapsed or updates are forced `

 So I tried what @cjmyers proposed here:

> git clone https://github.com/SynBioDex/libSBOLj.git <https://github.com/SynBioDex/libSBOLj.git>
cd libSBOLj
mvn install
cd ..
git clone https://github.com/SynBioDex/SBOLDesigner.git <https://github.com/SynBioDex/SBOLDesigner.git>
cd SBOLDesigner
mvn install
cd ..
https://github.com/MyersResearchGroup/iBioSim.git <https://github.com/MyersResearchGroup/iBioSim.git>
cd iBioSim
mvn install
cd ..
cd synbiohub
cd java
mvn package

That also hasn't worked, because while libSBOLj built, iBioSim failed to do so. I then tried this in the iBioSim repository:

```
mvn clean
mvn install
```

As we talked about a few days ago, to try and get iBioSim to build. This gave me a NullPointerException:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (attach-javadoc) on project iBioSim-conversion: Execution attach-javadoc of goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar failed.: NullPointerException`

Any idea what could be causing this, and how it could be fixed?

Thanks in advance!

**Comment by cjmyers** [comment]
We’ve put libSBOLj, SBOLDesigner, and iBioSim up on sonatype, so you should not need all these steps anymore.  We are still waiting to get some dependencies posted for iBioSim-conversion, so before that is done, you need to obtain those via the following steps:

1) Make sure you have the latest synbiohub (git pull in that directory)
2) Make sure you have the latest iBioSim (git pull in that directory)
3) “mvn clean” in the iBioSim directory, this will copy over the missing dependencies to your local maven repo.
4) Go to your synbiohub/java directory, do “mvn package”

At this point, you should be able start synbiohub.  Please let us know if this does not work.  James reports that it worked for him.

**Comment by chrisAta** [comment]
```
chris@claudette ~/D/D/s/java> mvn package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.synbiohub:SynBioHub:jar:1.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 10, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building SynBioHub Java components 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://mvn.sems.uni-rostock.de/snapshots/org/sbolstandard/libSBOLj/2.2.2-SNAPSHOT/maven-metadata.xml
Downloading: http://mvn.sems.uni-rostock.de/snapshots/org/sbolstandard/libSBOLj-parent/2.2.2-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/sbolstandard/libSBOLj-parent/2.2.2-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/org/sbolstandard/libSBOLj-parent/2.2.2-SNAPSHOT/maven-metadata.xml (608 B at 878 B/s)
Downloading: http://mvn.sems.uni-rostock.de/snapshots/edu/utah/ece/async/iBioSim-conversion/3.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://mvn.sems.uni-rostock.de/snapshots/edu/utah/ece/async/iBioSim-conversion/3.0.0-SNAPSHOT/iBioSim-conversion-3.0.0-SNAPSHOT.pom
[WARNING] The POM for edu.utah.ece.async:iBioSim-conversion:jar:3.0.0-SNAPSHOT is missing, no dependency information available
Downloading: http://mvn.sems.uni-rostock.de/snapshots/edu/utah/ece/async/iBioSim-conversion/3.0.0-SNAPSHOT/iBioSim-conversion-3.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.970 s
[INFO] Finished at: 2018-01-19T13:23:28Z
[INFO] Final Memory: 11M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project SynBioHub: Could not resolve dependencies for project org.synbiohub:SynBioHub:jar:1.0.0-SNAPSHOT: Could not find artifact edu.utah.ece.async:iBioSim-conversion:jar:3.0.0-SNAPSHOT in sems-maven-repository-snapshots (http://mvn.sems.uni-rostock.de/snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by cjmyers** [comment]
Sorry about that.  Zach committed the updated pom file to the wrong branch.

Please pull and try to build again.

**Comment by cjmyers** [comment]
Is this working now?
