### ISSUE TITLE
No Endpoint for Deleting Objects

### ISSUE THREAD

**Issue by nroehner** [SynBioHub/synbiohub#600]
It looks like there isn't any endpoint in the RESTful API for deleting objects from SynBioHub. This would be useful to have for testing purposes at least.

**Comment by cjmyers** [comment]
There are actually a remove endpoints, though it is not documented since it is indeed best only used for testing.  The endpoints are:

<URI>/remove

which removes an SBOL object with the specified URI, and

<URI>/removeCollection

which removes an SBOL collection and all its members with the specified URI (use with caution).  In both cases, the owner of the object must be logged in.

Note that the <URI> must be a private URI, since we normally do not allow public objects/collections to be removed.  If you need to remove public collections, then you need to add to config.local.json the following flag:

"removePublicEnabled": true,

This will allow the /removeCollection endpoint to work for public collections for admin users only.

Finally, libSBOLj does have a removeSBOL method.  This is only the /remove endpoint.

**Comment by cjmyers** [comment]
Supported in API now
