### ISSUE TITLE
Stacktrace when trying to view a component

### ISSUE THREAD

**Issue by palchicz** [SynBioHub/synbiohub#610]
h3. Steps to recreate
1. I made the following example design in SBOLDesigner (attached as .gz file)
[example_part.xml.gz](https://github.com/SynBioHub/synbiohub/files/1887710/example_part.xml.gz)
2. I created a new collection on SynBioHub
3. I uploaded the design
4. I navigated to the collections page and clicked the part name (demo_part in the picture below)
![image](https://user-images.githubusercontent.com/3741621/38470437-a6d36db8-3b17-11e8-8593-2e90565671c6.png)

h3. Expected Behavior
I expected to be taken to a page showing information about the component

h3. Actual Behavior
I get the following stack trace when I try to view a component in a collection I just made

```
Error
TypeError: Cannot read property 'toString' of undefined
    at sequence.sortedSequenceAnnotations.map (/home/deploy/synbiohub/node_modules/visbol/lib/getDisplayList.js:151:51)
    at Array.map (native)
    at getDisplayListSegment (/home/deploy/synbiohub/node_modules/visbol/lib/getDisplayList.js:126:66)
    at getDisplayList (/home/deploy/synbiohub/node_modules/visbol/lib/getDisplayList.js:12:9)
    at renderView (/home/deploy/synbiohub/lib/views/componentDefinition.js:365:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by zachzundel** [comment]
This may be an issue with VisBOL. Thanks for bringing it to my attention; I'll look into it.

**Comment by cjmyers** [comment]
You actually uncovered a couple of issues.  The first is fairly simple which is that it was unable to render because it could not find one of your parts on synbiohub.  It should though render this with a glyph indicating that it cannot find that part.  This was indeed a bug in visbol which I've fixed and updated synbiohub.org.  You should now be able to view your designs.  You don't need to reupload, they should simply now be viewable.

The second issue is how you ended up with a part that cannot be found in SynBioHub.  To do this, you added a part from the ACS collection.  The ACS collection though is not resident on SynBioHub.  It is accessed through a remote interface with the corresponding ICE repository.  SynBioHub is not currently able to fetch linked SBOL objects in remote repositories.  This is a separate issue that we need to figure out how to address.  A tricky issue for us on this one is that we are not guaranteed these objects won't change, be deleted, etc., since we do not have control of that repository.  One possible solution would be to provide you a copy of this object in your own namespace, so you would basically be cloning their object.  In this way, when you submitted, you would end up submitting this part into your local store, so you can be assured it will not change.  Alternatively, we can just link to the remote object and hope that it remains stable (very risky if the part is in a Benchling remote repo).  Will open a new issue for this point.

**Comment by palchicz** [comment]
That's great! And thanks for opening up another ticket.  Admittedly I was just playing around (trying to create random designs and seeing if anything broke)

**Comment by cjmyers** [comment]
And you succeeded on first try.  Well done :-)
