### ISSUE TITLE
v1.3 discards updates on dcterms:modified and annotations

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#654]
When an entry is updated in SynBioHub v1.2, it updates correctly with dcterms:modified and custom annotations.  The same update in SynBioHub v1.3, however, ignores the dcterms:modified and custom annotations, however.

For example, compare: 
https://synbiohub.utah.edu/user/jakebeal/scratch_test_collection/L0x2DTryptophan/1
https://hub.sd2e.org/user/sd2e/scratch_test_collection/ddh0x32o/1

(these are updated using precisely the same program, but the second is modified and the first is not).

**Comment by cjmyers** [comment]
Could you provide a share link for the Utah instance?  

FYI: Utah instance is actually from master branch on github.  Probably should update the version to make this more clear.

**Comment by jakebeal** [comment]
Share link: https://synbiohub.utah.edu/user/jakebeal/scratch_test_collection/L0x2DTryptophan/1/dbfb750767c8820a9805604146cab478ef52e14e/share

**Comment by cjmyers** [comment]
Is this the same code from Seattle?  Do you get any error messages/exceptions when you are trying to update the record?

**Comment by jakebeal** [comment]
It's an updated version of the overall codebase, but the particular SynBioHub interactions are the same.  I get no complaint from the interface---certainly no exceptions.  If there are more subtle messages, I don't know where they'd appear.

More to the point: when I run the exact same code pointed at the SD2 v1.2 instance, I get an update of dcterms:modified but not dcterms:title, while when I point at the Utah instance, I get an update of dcterms:title but not dcterms:modified.

**Comment by cjmyers** [comment]
In order to try to reproduce, let me make sure I have the exact steps correct:
1) Download an object from SBH
2) Change the URI prefix to your local namespace
3) Change the name of the object and/or modify annotations
4) Call addToCollection to an existing SBH collection with overwrite selected

Is this correct?  If so, it would be useful to have the SBOL file that you get from SBH from step 1, as well as the SBOL file that you are attempting to upload in step 4.

**Comment by cjmyers** [comment]
And perhaps also the SBOL file if you immediately redownload again.

**Comment by jakebeal** [comment]
Those steps are correct --- you can see the exact code if you wish at: https://gitlab.sd2e.org/jakebeal/SD2-Librarian

The SBOL file from step 1 is at the link above; the version being re-uploaded (and failing) is:
```
<?xml version="1.0" ?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:sbh="http://wiki.synbiohub.org/wiki/Terms/synbiohub#" xmlns:sbol="http://sbols.org/v2#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:ns0="http://sd2e.org#" xmlns:prov="http://www.w3.org/ns/prov#">
  <sbol:ComponentDefinition rdf:about="http://localhost/L0x2DTryptophan/1">
    <sbol:persistentIdentity rdf:resource="http://localhost/L0x2DTryptophan"/>
    <sbol:displayId>L0x2DTryptophan</sbol:displayId>
    <sbol:version>1</sbol:version>
    <dcterms:title>L-Tryptophan</dcterms:title>
    <dcterms:created>2018-07-29T12:30:45-05</dcterms:created>
    <sbh:ownedBy rdf:resource="https://synbiohub.utah.edu/user/jakebeal"/>
    <sbh:topLevel rdf:resource="http://localhost/L0x2DTryptophan/1"/>
    <ns0:stub_object>true</ns0:stub_object>
    <ns0:BioFAB_UID>tryptophan</ns0:BioFAB_UID>
    <dcterms:modified>2018-07-29T17:36:22-05</dcterms:modified>
    <sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#SmallMolecule"/>
  </sbol:ComponentDefinition>
</rdf:RDF>

```

**Comment by jakebeal** [comment]
In addition, v1.2 is merging (rather than replacing) annotations.
See, for example: https://hub.sd2e.org/user/sd2e/scratch_test_collection/ddh0x32o/1

**Comment by cjmyers** [comment]
Do you see this behavior with the Utah instance?

**Comment by jakebeal** [comment]
On the Utah instance, the annotations are not showing up at all, so I cannot tell you whether it would merge or replace them.

**Comment by cjmyers** [comment]
Ok, I can reproduce this.  Now just need to find a free moment to debug it.

**Comment by cjmyers** [comment]
Found the issue.  Turns out it was a subtle libSBOLj bug.  The problem was that before overwriting a record, it first checks if the record is different.  If it is not different, then it skips the overwrite to avoid re-uploading identical objects and wasting time.  However, libSBOLj had a bug in which it compared the annotation lists only one direction when doing the equals check.  So if the right set was a subset of the other, then it would still report equal by mistake, and thus skip the overwrite.  A potential workaround for SBH 1.2 is to also change the SBOL name field, as that will force the equal check to be false and the overwrite to take place.  

The fix to libSBOLj’s equals check has been deployed in 2.3.2-SNAPSHOT and rebuilding the java portion of SBH will get the fix.  I’ve done the update on synbiohub.utah.edu <http://synbiohub.utah.edu/>, so you should be able to test it there.

Note that the workaround on SBH 1.2 on the SD2 instance may run into the other issue you were seeing with union of annotations.

**Comment by jakebeal** [comment]
Thank you --- working like a charm on the Utah instance!  Now we just need to get the SD2 instance updated.
