### ISSUE TITLE
Edit fields in place

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#787]
Right now, the pattern for editing an object in SynBioHub is to download it, replace key fields, and upload it to replace the current object.  This works right around the "mutable" / "non-mutable" distinction, so it's kind of moot.

Why not allow us to edit all of the fields an object directly through the web interface, rather than just a select few?

**Comment by cjmyers** [comment]
This was an issue that we debated quite a bit in the early development of SynBioHub.  You are correct that a lot of the concern was about what would be allowed to change once it is put into SBH (i.e., what was mutable).  Note that the mutable fields we have remain mutable both in private repositories and in public ones.  I'm assuming you are not suggesting that we allow ALL fields in public records to be mutable, since this would defeat the purpose of having a permanent record that you can rely on.   

The other point that was argued was about feature creep for SynBioHub.  Namely, should it be a creator of data or just a repository for data.  We came down on the side that it should be the job of other software to actually be the creator of data.  I think your request comes from the fact that there is a sad lack of such tools out there currently.  Indeed, there is no tool available to edit large parts of SBOL currently.  However, those editors that do exist such as SBOLDesigner and iBioSim have worked well under the model of create/upload/download/edit/re-upload.

In any case, we can revisit this.  However, edits that involve more than simply text fields would involve some fairly substantial development.  For example, if you want to edit add a Component to a ComponentDefinition, you would need some interface like SBOLDesigner currently has to complete that task by fetching parts from a repo/file/etc.  

So, if you can narrow the scope a bit, I think we can do something soon, but if you want to edit everything, it is likely going to take some time.

**Comment by jakebeal** [comment]
Starting with text fields would be great for addressing my most immediate pain points, e.g., editing roles and types and adding/removing stub markers from Other Properties.

Note also that download/edit/re-upload has severe limitations at scale.  For example, when dealing with whole genomes or large and nested collections.

Basically, either we're going to, or else I'm going to need to start building tools that do surgery directly on the triple store, and I don't think that's in the desired model.

**Comment by cjmyers** [comment]
Agreed.  We don't want surgery on the triple store.  We can prioritize edit support for the fields you mention.  Tags without structure should not be difficult to do.

**Comment by zachzundel** [comment]
I think we should close this task since it is being specified into sub tasks.

**Comment by cjmyers** [comment]
Agreed
