### ISSUE TITLE
Allow deletion from a collection

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#809]
When a collection member gets deleted but somehow not deleted from the collection, it becomes a "ghost" element on SynBioHub that can't be deleted.  Can we allow one to delete at the collection level, not just when looking at the individual part?

**Comment by cjmyers** [comment]
This seems reasonable to me.  I don't think it would be too difficult.

**Comment by cjmyers** [comment]
@jakebeal we have this implemented in a branch, but it has raised some tricky semantic questions.  Right now, the functionality of delete on the collection page is acting the same as if you are on the page itself.  Namely, deleting an object, deletes that object and all references to that object.  This seems intuitive when you are on the page for the object, but it may not be intuitive when you delete from the collection page.

For example, assume you have an object X, that was submitted into private collection A while another private collection B also refers to X.  Now, when you are viewing either A or B, and you delete X, it will be deleted from the triple store as well as from both collections A and B.   Furthermore, if you have a public object Y that is a member of private collection A, and you try to delete it, nothing happens at all, since removal of public objects is not allowed.  This behavior seems non-intuitive.

Alternatively, we considered that delete on the collection page would only remove the member links to the object, but leave the object in place.  This would mean in the examples above, if you delete public object Y from A, that the member link would now be removed, which is allowed and seems to make sense.  If you delete X from A, it will still be referenced in B.  However, if you then go and delete X from B also, then you end up with X not being a member of any collection.  It can still show up in searches, but it seems odd to have a dangling object, and it also seems like it is different than what you wanted above, since the object can still only be deleted by going to its page.

Another option, would be to augment the approach above with a sort of garbage collection.  Namely, if you have deleted X from all collections that have it as a member, then the object itself would be deleted too.  

Or a variation on this would be that if you delete it from A (i.e., the collection it was submitted into and shares a URI prefix), then it always gets deleted (i.e., same behavior as navigating to the part), but when you delete it from a collection that does not share a URI prefix, then it only has its member referenced removed.  This is more like the symlink view of the world, where deletion of symlinks does not delete the object.

The current approach is likely the least intuitive (i.e., same as remove on the object page).  The remove only member links is intuitive but likely will leave a lot of dangling objects.  The garbage collection approach is perhaps the most intuitive but trickiest to implement.  Finally, the symlink approach is likely not too difficult to implement and at least somewhat intuitive.

Interested in your input on this one.

**Comment by jakebeal** [comment]
@cjmyers Well, we certainly don't want orphans.  There's at least two straightforward ways to deal with that from a UI perspective: 

- "remove from collection" warns you that it will delete, since this is the last collection the object is in
- "remove from collection" is greyed out if it would result in deletion/orphanage

I don't have any strong opinion which is better.
