### ISSUE TITLE
Allow URL attachments 

### ISSUE THREAD

**Issue by 3ach** [SynBioHub/synbiohub#913]
Per @jakebeal 's request

**Comment by cjmyers** [comment]
I would like to get some clarity on this, so I will explain the way I understand this.

1) Each page would have a new dropdown called "External Attachments", and instead of "Select File", it would have a button to "Create an External Attachment".

2) This would present either a pop-up window or new page to query for some information about this external attachment (do you want pop-up or new page?).  The information required would be similar to a submit, namely an id, name, and description.  It would also ask for a URL for the external attachment, and an optional size and hash.  Finally, it would have an optional type, perhaps from a dropdown list from EDAM or PURL, but likely need an option to provide a URI for your format.  Free text URI may be the easiest solution for this initially.

3) Once the data is provided, it would create an Attachment object (using a slightly modified addAttachmentToTopLevel in attachments.js), and link this to the topLevel that this process was all started with.

**Comment by zachzundel** [comment]
I am not sure the extra pop-up flow is necessary. You could have a simple inline form with 'name' and 'url' fields. It would then query the URL for the resulting artifact, calculate the size and hash, use the Content-Type in the HTTP response as the type, and then save the resulting changes. The ID could come from an ID-ified name like we do for submission.

**Comment by cjmyers** [comment]
I’m not sure about querying the URL for this information.  Are we sure that the URL will always be dereferenable and will return something that we can understand?

**Comment by jakebeal** [comment]
In general, I agree with this workflow.

Querying the URL is desirable, but may not be feasible. Consider:
1. Linking to something in Agave or another access-controlled storage environment, which may need tokens that SynBioHub won't have available to it.
2. Many external things will be that way because they are quite large (e.g., reference genomes, FCS files, microscopy data).

Accordingly, I believe this should _not_ give an option for entering hash or size. Since SynBioHub doesn't control the resource, there's no reason for either hash or size to remain stable from one access to another. Consider linking to a reference genome in GenBank, which may be updated at unpredictable intervals.

I agree with @zachzundel, however, that we don't need a popup or a new page: this can be handled readily enough with an inline form.

**Comment by cjmyers** [comment]
Ok, so name and URL.  What about description and format?

**Comment by jakebeal** [comment]
They're both optional of course, so if something's awkward, no need to fret about it. That's particularly so for description, since we currently don't do it for locally stored attachments.

Format seems like it could to be a dropdown of common types or "other", which allows one to enter a URL.

**Comment by zachzundel** [comment]
The work so far:
 - Form accepts a URL
 - Attempts to resolve the URL and get the `Content-Type` header of the response. If successful, fills this in as the type
 - If the query fails, tries to pull filename and extension from the URL
 - In all cases, the type is then available for editing or correction by the user

I need to add:
 - Attachment name (I don't think it's strictly required, but probably better than random initial names.)
 - Finish backend for making attachment

You can track the development in the `url-attachments` branch

**Comment by cjmyers** [comment]
Sounds great.  Thanks.
